title: "Amrth Narayan"
description: "Final Year Law Student | Taxation & Corporate Law"
baseurl: ""
url: "https://amrthnarayan.github.io"

markdown: kramdown
theme: null

author:
  name: "Amrth Narayan"
  email: "Amrth16@gmail.com"
